package org.rssb.phonetree.status;


public enum FamilyActionResponse implements ActionResponseType{
    FAMILY_DOES_NOT_EXISTS,
    FAMILY_MEMBER_HAS_ASSIGNED_SEVA,
    FAMILY_SAVED_SUCCESSFULLY,
    FAMILY_SAVED_ERROR,
    FAMILY_MEMBER_SUCCESSFULLY_MOVED_UNDER_OTHER_FAMILY,
    FAMILY_MEMBER_SUCCESSFULLY_MOVED_AS_SEPARATE_FAMILY,
    FAMILY_SUCCESSFULLY_DELETED,
    FAMILY_SELECT_BEFORE_ACTION,
    FAMILY_CONFIRM_BEFORE_REMOVE;
}
