package org.rssb.phonetree.status;


public enum MemberActionResponse implements ActionResponseType{
    MEMBER_SUCCESSFULLY_DELETED,
    MEMBER_DOES_NOT_EXISTS,
    MEMBER_HAS_ASSIGNED_SEVA,
    MEMBER_SELECT_BEFORE_ACTION,
    MEMBER_CONFIRM_BEFORE_REMOVE,
    MEMBER_CONFIRM_BEFORE_MOVE_UNDER_OTHER_FAMILY,
    MEMBER_CONFIRM_BEFORE_MOVE_AS_SEPARATE_FAMILY;
}
