package org.rssb.phonetree.status;


public enum SevadarActionResponse implements ActionResponseType{
    SEVADAR_ALREADY_EXISTS,
    FAMILY_MEMBER_EXISTS_AS_SEVADAR,
    SEVADAR_SUCCESSFULLY_ADDED,
    FAMILY_MEMBER_ALREADY_ASSIGNED_SEVADAR_SEVA,
    SEVADAR_HAS_SEVADARS_ASSIGNED,
    SEVADAR_SUCCESSFULLY_DELETED,
    SEVADAR_SUCCESSFULLY_REPLACED,
    SEVADAR_HAS_BEEN_SWAPPED,
    SEVADAR_SUCCESSFULLY_MOVED_UNDER_OTHER_TEAM_LEAD,
    SEVADAR_SELECT_BEFORE_ACTION,
    SEVADAR_CONFIRM_BEFORE_REMOVE,
    SEVADAR_SELECT_TEAM_LEAD_BEFORE_ACTION,
    SEVADAR_SELECT_DIFFERENT_SEVADARS_TO_SWAP,
    SEVADAR_CANNOT_SWAP_SEVADARS_UNDER_SAME_TEAM_LEAD,
    SEVADAR_CANNOT_MOVE_UNDER_SAME_TEAM_LEAD,
    SEVADAR_IS_ALREADY_TEAM_LEAD_BACKUP,
    SEVADAR_CONFIRM_BEFORE_CHANGE_TEAM_LEAD_BACKUP,
    SEVADAR_SUCCESSFULLY_CHANGED_AS_BACKUP_TEAM_LEAD;

    /*@Override
    public String getMessage() {
        return ResourceBundle.getBundle("messages").getString(this.toString().toLowerCase());
    }*/
}
