spring:
  datasource:
    url: jdbc:sqlite:C:\Rajesh\Personal\Satsang\Test.db
    password:
    username:
    driver-class-name: org.sqlite.JDBC
---

spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLiteDialect
        show_sql: true
        format_sql: true
        type: debug
        enable_lazy_load_no_trans: true
---

logging:
  level:
    org:
      hibernate:
        SQL: debug
        type: trace
---


spring:
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
---

org:
  rssb:
    phonetree:
      seceratery-name: Sanjay:Phanda:Secretory
      admin-names: Rajesh:Khullar:Phone Tree Admin,Meena:Padnani:Team Lead Monitor,Vineet:Sharma:Phone Tree Admin
      file-password-protection: RSSBAA
      list-output-directory: C:\Rajesh\Output\List
