spring:
  datasource:
    url: jdbc:sqlite:C:\Rajesh\Personal\Satsang\SQLite\PhoneTree
    password:
    username:
    driver-class-name: org.sqlite.JDBC
---

spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLiteDialect
        show_sql: true
        format_sql: true
        type: debug
        enable_lazy_load_no_trans: true
---

logging:
  level:
    org:
      hibernate:
        SQL: debug
        type: trace
---


spring:
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
---
